server.port: 9090
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/timetracker
    username: postgres
    password: "Halloking1234!"
    driverClassName: org.postgresql.Driver
